# Generated by Django 6.1 on 2026-08-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkGDZhFXH3-X5rNYfs8UjxfNCI-EWnsjhNA7TdMrFMVA&s=10', max_length=200)),
                ('cuisine', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=20)),
            ],
        ),
    ]
