# Generated by Django 6.1 on 2026-08-19 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_restaurant_picture_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='vegeterian',
            new_name='vegetarian',
        ),
    ]
